platform :ios, '8.0'

pod 'AFNetworking'
#pod 'CrashlyticsFramework'
#pod 'Fabric', '~> 1.2'
pod 'CocoaLumberjack', '~> 2.0'
#pod 'CrashlyticsLumberjack', '2.0.1-beta'
pod 'JGProgressHUD'
pod 'libextobjc'       # Useful macros and some craziness
pod 'KVOController', '~> 1.0.3'
pod 'Bolts', '~> 1.2.0'
pod 'INTULocationManager', '~> 3.0.1'
pod 'hpple', '~> 0.2'
pod 'BlocksKit', '~> 2.2'
# pod 'Masonry', '~> 0.6'
# pod 'SparkInspector', '~> 1.3'
pod 'MTDates', '~> 1.0'
# pod 'AnimatedGIFImageSerialization', '~> 0.2'
pod 'apptentive-ios', '~> 1.7'
pod 'ReactiveCocoa', '2.5'
pod 'AMRatingControl', '~> 1.3'
pod 'JSONModel', '~> 1.0.2'
pod 'UITableView-NXEmptyView', '~> 0.1.7'
pod 'Mixpanel', '~> 2.8'
pod 'Tweaks', '~> 2.0.0'
pod 'PureLayout', '~> 2.0.6'
pod 'Parse', '~> 1.7.5.3'
pod 'TOWebViewController', '~> 2.0.14'
pod 'GPUImage'
pod 'JCTagListView'
pod 'WeixinActivity', '~>1.2.0'
#pod 'GNMapOpener', '~> 0.0'